cabal-version:      3.0
name:               plutus
version:            0.1.0.0
build-type:         Simple

executable plutus-server
  main-is:          Main.hs
  hs-source-dirs:   app
  default-language: Haskell2010
  ghc-options:      -Wall -Wcompat -threaded -rtsopts -with-rtsopts=-N
  build-depends:
      aeson
    , base >= 4.18 && < 5
    , bytestring
    , containers
    , http-types
    , http-api-data
    , postgresql-simple
    , scientific
    , servant
    , servant-server
    , text
    , time
    , transformers
    , wai
    , warp
