-- Assets available when a Book is created. The list includes ISO currencies
-- retained for historic ledgers plus the precious-metal and Bitcoin codes
-- already supported by Njord. Book-specific commodities are added later.
CREATE OR REPLACE TEMP VIEW njord_asset_catalog (id) AS
SELECT regexp_split_to_table(
    'XAG XAU XPD XPT XBT
     AED AFN ALL AMD ANG AOA ARS ATS AUD AWG AZN BAM BBD BDT BEF BGN BHD BIF
     BMD BND BOB BRL BSD BTN BWP BYR BZD CAD CDF CHF CLP CNY COP CRC CUC CUP
     CVE CYP CZK DJF DKK DMK DOP DZD EEK EGP ESP ETB EUR FIM FJD FKP GBP GEL
     GHS GIP GMD GNF GRD GTQ GYD HKD HNL HRK HTG HUF IDR IED ILS INR IQD
     IRR ISK ITL JMD JOD JPY KES KGS KHR KMF KPW KRW KWD KYD KZT LAK LBP
     LKR LRD LSL LTL LUF LVL LYD MAD MDL MGA MKD MMK MNT MOP MRO MTL MUR
     MVR MWK MXN MYR MZN NAD NGN NIO NLG NOK NPR NZD OMR PAB PEN PGK PHP PKR
     PLN PTE PYG QAR RON RSD RUB RWF SAR SBD SCR SDG SEK SGD SHP SIT SKK SLL
     SOS SRD STD SVC SYP SZL THB TMM TND TOP TRY TTD TWD TZS UAH UGX USD UYU
     VEB VND VUV WST XAF XCD XOF XPF YER ZAR ZMK ZWD',
    '\s+'
)::VARCHAR;
