\ir drop.sql
\ir schema.sql
\ir currencies.sql
\ir reference-data.sql
\ir updating.sql
\ir reports.sql
\ir api-foundation.sql
\ir uk-business.sql
\ir panama.sql
\ir taiwan.sql
\ir jurisdictions.sql
\ir api.sql
